<?php
// Variables
return [
    'First Time Buyer Mortgages' => [
        'first time buyer mortgages',
        'happy young person with door key',
        'happy young couple standing outside house',
        'holding door key',
        'happy person with thumbs up',
        'confused person',
        'person with question mark',
    ],
    'Remortgages' => [
        'remortgage',
        'piggy bank',
        'save money',
        'savings',
        'clock',
        'times up',
        'time is now',
        'holding door key',
        'mortgage broker',
        'happy person or couple with thumbs up',
    ],
    'Home Movers' => [
        'move home',
        'moving home',
        'for sale sign outside house',
        'holding door key',
        'mortgage broker',
        'happy person or couple with thumbs up',
    ],
    'Buy To Let' => [
        'buy to let',
        'landlord',
        'renting',
        'limited company',
        'business owner',
        'mortgage broker',
    ],
    'Mortgage Protection' => [
        'life insurance',
        'critical illness',
        'health',
        'family protection',
        'income protection',
        'protect income',
        'protect house',
        'protect family',
    ],
    'Days' => [
        'national day',
    ],
    'General Insurance' => [
        'protect home',
        'home insurance',
        'accidents in the home',
    ],
    'Adverse Credit' => [
        'bad credit',
        'poor credit',
        'credit score',
        'happy person with thumbs up',
        'confused person',
        'person with question mark',
        'sad person',
    ],
    'Self Employed' => [
        'business owner',
        'self employed',
        'boss',
        'manager',
        'company accounts',
        'hmrc',
        'tax return',
        'happy middle-aged person with thumbs up',
    ],
    'Other Mortgage Related' => [
        'key workers',
        'nurses',
        'doctors',
        'uk police',
        'uk firefighters',
        'uk military',
        'armed forces',
        'right to buy',
        'happy couple over 60 years old',
    ],
];

